job_roles = ["Angular Developer", "Angular JS Developer", "Associate Software Engineer", "Backend Developer", "C# Developer",
"C++ Developer", "Developer", "Client-Side Developer", "Embedded Software Developer", "Embedded Software Engineer",
"Front End Web Developer", "Front-End Developer", "Frontend Angular Developer", "Frontend Architect",
"Frontend Developer", "Frontend Engineer", "Frontend Web Developer", "Full Stack Developer",
"Full Stack Java Developer", "Full Stack Software Engineer", "HTML Developer", "Java Backend Developer",
"Java Developer", "Java Fullstack Developer", "Java Microservices Developer", "Java React Developer",
"Java SpringBoot Developer", "Javascript Developer", "Junior Software Developer", "Junior Software Engineer",
"Mean Stack Developer", "MERN Stack Developer", "MIS", "MIS Analyst", "MIS Executive and Analyst",
"Node JS Developer", "Node.js Developer", "Python Developer", "Python/Django Developer", "React Developer",
"React Js Developer", "React.js Developer", "React/Frontend Developer", "React+Node Js Developer",
"RIM Support Engineer", "Ruby on Rails Developer", "SAP HANA DB Administration Software Development Engineer",
"Software Developer", "Software Development Engineer", "Software Engineer", "Software Engineer Trainee",
"Software Programmer", "Solution Developer", "SYBASE Database Administration Software Development Engineer",
"Trainee Associate Engineer", "Trainee Software Developer", "Trainee Software Engineer", "UI Angular Developer",
"UI Developer", "UI Frontend Developer", "UI/Frontend Developer", "UI/UX Developer", "Web and Software Developer",
"Web Designer & Developer", "Web Designer and Developer", "Web Designer/Developer", "Web Developer",
"Web Developer and Designer", "Website Designer", "website developer", "XML and C# Developer", "PHP Developer",
"Laravel Developer", "Magento Developer", "Drupal Developer", "Dotnet developer", ".net ", "Vue.JS Developer",
"Python/Django Developer", "GoLang developer", "jQuery", "Springboot Developer", "Actuarial Analyst", "Analyst",
"AR Analyst", "Associate Business Analyst", "Automation Test Analyst", "Azure Data Engineer", "Big Data Engineer",
"Business Analyst", "Business Data Analyst", "Data Analyst", "Data Analytics Trainer", "Data Research Analyst",
"Data Researcher", "Data Science Engineer", "Data Scientist", "Database Administrator", "Functional Analyst",
"Junior Analyst", "Junior Research Analyst", "KYC Analyst", "Market Research Analyst", "Power BI Developer",
"Product Analyst", "Programmer Analyst", "QA Analyst", "Quality Analyst", "Real Time Analyst",
"Reconciliation Analyst", "Research Analyst", "Risk Analyst", "Sales Analyst", "Salesforce Business Analyst",
"Service Desk Analyst", "SOC Analyst", "SQL Developer", "Android Application Developer", "Android Developer",
"Android Mobile Application Developer", "Application Developer", "Application Support Engineer",
"Flutter Developer", "iOS Application Developer", "IOS Developer", "Mobile App Developer",
"Mobile Application Developer", "Associate Technical Support Engineer", "Automation Engineer",
"Automation Test Engineer", "Batch Support Engineer", "Desktop Support Engineer", "Genesys Support Engineer",
"IT Support Engineer", "Network Support Engineer", "QA Automation Engineer", "SaaS Support Engineer",
"Security Engineer", "Test Automation Engineer", "Systems Support Engineer",
"Software Development Engineer - Test", "Software Test Engineer", "Software Tester", "Support Engineer",
"Tech Customer Support Engineer", "Technical Support Engineer", "Servicenow Developer", "SharePoint Developer",
"Shopify Developer", "Unity Game Developer", "WordPress & Shopify Developer", "WordPress Developer",
"Wordpress Web Developer", "Unreal Developer","Analyst","Analytical",
    "analytical skill",
    "Analytical Skills",
    "Analytics",
    "BeautifulSoup",
    "big data",
    "Bigcommerce",
    "BIGDATA",
    "Business analysis",
    "Business process",
    "Business Process Management",
    "Business Requirement Analysis",
    "Caffe",
    "cassandra",
    "Consulting",
    "CuDNN",
    "data acquisition",
    "Data analysis",
    "Data Architecture",
    "Data Engineer",
    "Data Engineering",
    "Data Factory",
    "data governance",
    "Data Loader",
    "Data Management",
    "Data Migration",
    "Data modeling",
    "Data Models",
    "data pipeline architecture",
    "Data processing",
    "data protection",
    "Data quality",
    "data science",
    "Data validation",
    "Data verse in PowerAERROR!",
    "data warehouse",
    "Data-Binding",
    "Database Design",
    "Database management",
    "Database Schema",
    "DAX queries",
    "Db2",
    "Dynamo Db",
    "ETL",
    "ETL design",
    "Excel",
    "Hadoop",
    "IT Security Analyst",
    "Lambda/function",
    "mangodb",
    "microsoft",
    "Microsoft Azure",
    "Microsoft azure data factory",
    "Mongo DB",
    "MongoDB",
    "MS Access",
    "MS Office",
    "MS SQL",
    "Ms Sql Database",
    "Ms Sql Serve",
    "MSMQ",
    "MSSQL",
    "Mysq",
    "MySQL",
    "MySQL. HTML",
    "NLP",
    "NoSQL",
    "OpenCV",
    "Phyton",
    "Pinecone DB",
    "PL/SQL",
    "PLSQL",
    "Postgres",
    "Postgresql",
    "Power BI",
    "Problem Solving",
    "Problem Solving & Analytical Skills",
    "Process Analytics",
    "PySpark",
    "Python",
    "Python Development",
    "Python Framework",
    "python progaraming",
    "RDBMS",
    "Rdbms Concepts",
    "RDS",
    "redshift",
    "Relational database",
    "relational databases",
    "Scala",
    "scrapy",
    "scrapy framework",
    "Spark",
    "SQL",
    "SQL Azure",
    "SQL Database",
    "sql knowledge",
    "SQL queries",
    "SQL Server",
    "SQL Server ASP.Net",
    "SQL Server Development",
    "SQLit",
    "SQLite",
    "SQLite Database",
    "sqs",
    "SSIS",
    "SSRS",
    "Stored procedures",
    "tableau",
    "TensorFlow",
    "Theano",
    "Torch",
    "Triggers",
    "Advanced Excel",
    "BA",
    "business Analyst",
    "Business Analytics",
    "Business Intelligence (BI)",
    "data analyst",
    "data analytics",
    "data cleansing",
    "Data Scraping",
    "Database",
    "Database Planning",
    "database structures",
    "Databases Postgres",
    "ETL Tool",
    "Extraction",
    "Fabrication",
    "Google Analytics",
    "H look up",
    "macros",
    "Management Information System",
    "Microsoft applications",
    "MIS",
    "MS SQLServer",
    "MS-Excel",
    "Nosql Databases",
    "numpy",
    "Outlook",
    "panda",
    "PowerPoint.",
    "Qlik",
    "query",
    "Regression testing",
    "Regular Expressions",
    "spreadsheets",
    "statistical analyses",
    "vlook up",
    "Warehousing",
    "WCF Data Services",
    "Word",
    "AI",
    "analysis",
    "Analysts",
    "Associate Analyst",
    "bi",
    "Bi Tools",
    "BigQuery",
    "business analyst bpo",
    "business intelligence",
    "Business operations",
    "business process analysis",
    "business requirements",
    "Business Research",
    "Business services",
    "business system",
    "Concatenate",
    "CouchD",
    "dashboards",
    "Data collection",
    "data collection systems",
    "Data communication",
    "Data entry operation",
    "data integrity",
    "Data Mapping",
    "data mining",
    "Data Reporting",
    "Data Sciences",
    "data visualization",
    "Data warehousing",
    "Database Management System",
    "Database testing",
    "DB",
    "dbms",
    "deep learning",
    "excel google analytics",
    "Google Sheets",
    "hlookup",
    "Index Optimization",
    "IT Business Analyst",
    "IT Consulting",
    "IT Management",
    "IT Operations Management",
    "looker",
    "Mango Db",
    "Marketing analytics",
    "Marketing operations",
    "Mathematics",
    "Memcached",
    "Microstrategy",
    "MIS documentation",
    "Mis Report Preparation",
    "MIS reporting",
    "Ms excel",
    "Natural language processing",
    "Php And Mysql",
    "Php Codeigniter",
    "Pivot",
    "pivot table",
    "PL-SQL",
    "Portfolio management",
    "postgrest",
    "Power Query",
    "Powerpoint",
    "predictive analytics",
    "prescriptive analytics",
    "Python or PHP",
    "R",
    "Reporting tools",
    "Risk analysis",
    "SAS",
    "Schema",
    "Senior Analyst",
    "Site Analysis",
    "Snowflake DB",
    "SPSS",
    "Statistical process control",
    "Statistical Tools",
    "statistics",
    "System analysis",
    "Systems Analysis",
    "T-SQL",
    "Teradata",
    "VB SCRIPT",
    "VBA",
    "vlookup",
    "Webmaster",
    "Website Analysis",
    "zoho analytics"]