job_roles = ["Angular Developer", "Angular JS Developer", "Associate Software Engineer", "Backend Developer", "C# Developer",
"C++ Developer", "Developer", "Client-Side Developer", "Embedded Software Developer", "Embedded Software Engineer",
"Front End Web Developer", "Front-End Developer", "Frontend Angular Developer", "Frontend Architect",
"Frontend Developer", "Frontend Engineer", "Frontend Web Developer", "Full Stack Developer",
"Full Stack Java Developer", "Full Stack Software Engineer", "HTML Developer", "Java Backend Developer",
"Java Developer", "Java Fullstack Developer", "Java Microservices Developer", "Java React Developer",
"Java SpringBoot Developer", "Javascript Developer", "Junior Software Developer", "Junior Software Engineer",
"Mean Stack Developer", "MERN Stack Developer", "MIS", "MIS Analyst", "MIS Executive and Analyst",
"Node JS Developer", "Node.js Developer", "Python Developer", "Python/Django Developer", "React Developer",
"React Js Developer", "React.js Developer", "React/Frontend Developer", "React+Node Js Developer",
"RIM Support Engineer", "Ruby on Rails Developer", "SAP HANA DB Administration Software Development Engineer",
"Software Developer", "Software Development Engineer", "Software Engineer", "Software Engineer Trainee",
"Software Programmer", "Solution Developer", "SYBASE Database Administration Software Development Engineer",
"Trainee Associate Engineer", "Trainee Software Developer", "Trainee Software Engineer", "UI Angular Developer",
"UI Developer", "UI Frontend Developer", "UI/Frontend Developer", "UI/UX Developer", "Web and Software Developer",
"Web Designer & Developer", "Web Designer and Developer", "Web Designer/Developer", "Web Developer",
"Web Developer and Designer", "Website Designer", "website developer", "XML and C# Developer", "PHP Developer",
"Laravel Developer", "Magento Developer", "Drupal Developer", "Dotnet developer", ".net ", "Vue.JS Developer",
"Python/Django Developer", "GoLang developer", "jQuery", "Springboot Developer", "Actuarial Analyst", "Analyst",
"AR Analyst", "Associate Business Analyst", "Automation Test Analyst", "Azure Data Engineer", "Big Data Engineer",
"Business Analyst", "Business Data Analyst", "Data Analyst", "Data Analytics Trainer", "Data Research Analyst",
"Data Researcher", "Data Science Engineer", "Data Scientist", "Database Administrator", "Functional Analyst",
"Junior Analyst", "Junior Research Analyst", "KYC Analyst", "Market Research Analyst", "Power BI Developer",
"Product Analyst", "Programmer Analyst", "QA Analyst", "Quality Analyst", "Real Time Analyst",
"Reconciliation Analyst", "Research Analyst", "Risk Analyst", "Sales Analyst", "Salesforce Business Analyst",
"Service Desk Analyst", "SOC Analyst", "SQL Developer", "Android Application Developer", "Android Developer",
"Android Mobile Application Developer", "Application Developer", "Application Support Engineer",
"Flutter Developer", "iOS Application Developer", "IOS Developer", "Mobile App Developer",
"Mobile Application Developer", "Associate Technical Support Engineer", "Automation Engineer",
"Automation Test Engineer", "Batch Support Engineer", "Desktop Support Engineer", "Genesys Support Engineer",
"IT Support Engineer", "Network Support Engineer", "QA Automation Engineer", "SaaS Support Engineer",
"Security Engineer", "Test Automation Engineer", "Systems Support Engineer",
"Software Development Engineer - Test", "Software Test Engineer", "Software Tester", "Support Engineer",
"Tech Customer Support Engineer", "Technical Support Engineer", "Servicenow Developer", "SharePoint Developer",
"Shopify Developer", "Unity Game Developer", "WordPress & Shopify Developer", "WordPress Developer",
"Wordpress Web Developer", "Unreal Developer"]