#
# Copyright (c) 2023 Airbyte, Inc., all rights reserved.
#


import json
from datetime import datetime
from typing import Dict, Generator

from airbyte_cdk.logger import AirbyteLogger
from airbyte_cdk.models import (
    AirbyteCatalog,
    AirbyteConnectionStatus,
    AirbyteMessage,
    AirbyteRecordMessage,
    AirbyteStream,
    ConfiguredAirbyteCatalog,
    Status,
    Type,
)
from airbyte_cdk.sources import Source


class SourceInstahyreJobScrapper(Source):
    def check(self, logger: AirbyteLogger, config: json) -> AirbyteConnectionStatus:
        """
        Tests if the input configuration can be used to successfully connect to the integration
            e.g: if a provided Stripe API token can be used to connect to the Stripe API.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.yaml file

        :return: AirbyteConnectionStatus indicating a Success or Failure
        """
        try:
            import requests
            url = "https://www.instahyre.com/api/v1/job_search?company_size=0&isLandingPage=true&job_categories=1&job_categories=8" \
                "&job_categories=10&job_type=0"
            requests.get(url)
            return AirbyteConnectionStatus(status=Status.SUCCEEDED)
        except Exception as e:
            return AirbyteConnectionStatus(status=Status.FAILED, message=f"An exception occurred: {str(e)}")

    def discover(self, logger: AirbyteLogger, config: json) -> AirbyteCatalog:
        from .streams_schema import stream_schema

        return AirbyteCatalog(streams=stream_schema)

    def read(
        self, logger: AirbyteLogger, config: json, catalog: ConfiguredAirbyteCatalog, state: Dict[str, any]
    ) -> Generator[AirbyteMessage, None, None]:
        """
        Returns a generator of the AirbyteMessages generated by reading the source with the given configuration,
        catalog, and state.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
            the properties of the spec.yaml file
        :param catalog: The input catalog is a ConfiguredAirbyteCatalog which is almost the same as AirbyteCatalog
            returned by discover(), but
        in addition, it's been configured in the UI! For each particular stream and field, there may have been provided
        with extra modifications such as: filtering streams and/or columns out, renaming some entities, etc
        :param state: When a Airbyte reads data from a source, it might need to keep a checkpoint cursor to resume
            replication in the future from that saved checkpoint.
            This is the object that is provided with state from previous runs and avoid replicating the entire set of
            data everytime.

        :return: A generator that produces a stream of AirbyteRecordMessage contained in AirbyteMessage object.
        """
        import requests

        # Instahyre
        url = "https://www.instahyre.com/api/v1/job_search?company_size=0&isLandingPage=true&job_categories=1&job_categories=8" \
              "&job_categories=10&job_type=0"
        total_jobs_counts = int(requests.get(url).json()['meta']['total_count'])

        for offset in range(0, total_jobs_counts, 10):
            new_url = url + f"&offset={offset}"
            try:               
                jobs = requests.get(new_url).json()['objects']

                for job in jobs:
                    location_name = job.get('locations') or ""
                    employer = job.get('employer') or ""
                    if employer:
                        company_name = employer.get('company_name') or ''
                        company = {
                            "name": company_name
                        }
                        yield AirbyteMessage(
                                type=Type.RECORD,
                                record=AirbyteRecordMessage(
                                        stream='companies', data=company, emitted_at=int(datetime.now().timestamp()) * 1000
                                )
                        )
                    else:
                        company_name = ""

                    job_url = job.get('public_url') or ''

                    if job_url:
                        job_id = job_url.split("/")[-2].split("-")[1]
                        job_opening_api_url = f"https://www.instahyre.com/api/v1/employer_public_jobs/{job_id}"
                        try:
                            job_response = requests.get(job_opening_api_url).json()
                        except:
                            continue
                        job_opening = {
                            "job_role": "",
                            "job_title": job.get('candidate_title') or "",
                            "min_experience": job_response.get('workex_max') or "",
                            "max_experience": job_response.get('workex_min') or "",
                            "job_description_url": job_url,
                            "skills": {"preferredSkills": job_response.get('keywords') or []},
                            "min_ctc": "",
                            "max_ctc": "",
                            "department": job_response.get('job_category') or "",
                            "company": company_name,
                            "job_source": "instahyre",
                            "job_location": location_name,
                            "raw_response": job | job_response,
                            "job_description_url_without_job_id": job_url,
                            "job_description_raw_text": job_response.get('description') or ""
                        }

                        yield AirbyteMessage(
                                type=Type.RECORD,
                                record=AirbyteRecordMessage(
                                        stream='job_openings', data=job_opening, emitted_at=int(
                                                datetime.now().timestamp(
                                                )
                                        ) * 1000
                                ),
                        )

                        recruiter_details = {
                            "hiring_manager_for_job_link": job_url,
                            "name": job_response.get('recruiterName') or "",
                            "company": company_name,
                            "short_intro": job_response.get('recruiter_designation') or "",
                            "linkedin_profile_url": f"dummy_{company_name}"
                        }
                        yield AirbyteMessage(
                                type=Type.RECORD,
                                record=AirbyteRecordMessage(
                                        stream='recruiter_details', data=recruiter_details,
                                        emitted_at=int(datetime.now().timestamp()) * 1000
                                ),
                        )
                    else:
                        continue
            except Exception as e:
                print(f"Got {e} Error While Pulling Data")
